Issue
  { issueClosedAt = Just 2016 (-06) (-06) 10 : 26 : 37 UTC
  , issueUpdatedAt = 2016 (-06) (-06) 10 : 26 : 37 UTC
  , issueEventsUrl =
      URL
        "https://api.github.com/repos/jsdelivr/jsdelivr/issues/11982/events"
  , issueHtmlUrl =
      Just (URL "https://github.com/jsdelivr/jsdelivr/issues/11982")
  , issueClosedBy = Nothing
  , issueLabels = []
  , issueNumber = 11982
  , issueAssignees = []
  , issueUser =
      SimpleUser
        { simpleUserId = Id 513903
        , simpleUserLogin = N "propertunist"
        , simpleUserAvatarUrl =
            URL "https://avatars3.githubusercontent.com/u/513903?v=3"
        , simpleUserUrl = URL "https://api.github.com/users/propertunist"
        }
  , issueTitle =
      "adding new project fails: Failed to establish a new connection:Name or service not known"
  , issuePullRequest = Nothing
  , issueUrl =
      URL "https://api.github.com/repos/jsdelivr/jsdelivr/issues/11982"
  , issueCreatedAt = 2016 (-06) (-04) 14 : 22 : 59 UTC
  , issueBody =
      Just
        "i just started stepping through the guide for adding a new project and failed the very first hurdle!\ni created an info.ini file as instructed, but my PR for that file was rejected on the basis that my website is unreachable (which is not the case): \n\n```\nHTTPSConnectionPool(host='www.ureka.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -2] Name or service not known',))\n```\n\nin reality, my website is reachable presently from every location around the world that i have tested it from. is anyone able to provide any more information for me to resolve this issue?\nthanks\n"
  , issueState = StateClosed
  , issueId = Id 158506879
  , issueComments = 2
  , issueMilestone = Nothing
  }